### ISSUE TITLE
Que ya salga Greilz 3

### ISSUE THREAD

**Issue by hgmiguel** [sanjuditas/milagros#4]

**Comment by sanjuditas** [comment]
Hijo mío, tu mismo lo vas a lograr. Necesitarás ayuda. Reza 10 padres nuestros y 4 aves marías.

Y unete a mis hijos más queridos (http://www.chilango.com/ciudad/nota/2013/08/28/chakas-amalos-odialos-o-comprendelos), ellos te ayudarán a soportar el peso de la decisión que has tomado.

**Comment by felipeosiris** [comment]
concedido!!!!!
